export const ROLES = {
  SUPER_ADMIN:     'SUPER_ADMIN',
  SALES_MANAGER:   'SALES_MANAGER',
  SALES_EXECUTIVE: 'SALES_EXECUTIVE',
  MARKETING_MANAGER:'MARKETING_MANAGER',
  CONTENT_EDITOR:  'CONTENT_EDITOR',
}

export const PERMISSIONS = {
  // CRM
  VIEW_ALL_INQUIRIES:    'VIEW_ALL_INQUIRIES',
  VIEW_OWN_INQUIRIES:    'VIEW_OWN_INQUIRIES',
  ASSIGN_INQUIRY:        'ASSIGN_INQUIRY',
  UPDATE_INQUIRY_STATUS: 'UPDATE_INQUIRY_STATUS',
  ADD_INQUIRY_NOTE:      'ADD_INQUIRY_NOTE',
  DELETE_INQUIRY:        'DELETE_INQUIRY',
  EXPORT_CRM:            'EXPORT_CRM',
  // Products
  VIEW_PRODUCTS:         'VIEW_PRODUCTS',
  CREATE_PRODUCT:        'CREATE_PRODUCT',
  EDIT_PRODUCT:          'EDIT_PRODUCT',
  DELETE_PRODUCT:        'DELETE_PRODUCT',
  // Gallery
  VIEW_GALLERY:          'VIEW_GALLERY',
  CREATE_GALLERY:        'CREATE_GALLERY',
  EDIT_GALLERY:          'EDIT_GALLERY',
  DELETE_GALLERY:        'DELETE_GALLERY',
  // Users
  VIEW_USERS:            'VIEW_USERS',
  CREATE_USER:           'CREATE_USER',
  EDIT_USER:             'EDIT_USER',
  DELETE_USER:           'DELETE_USER',
  // Email Templates
  VIEW_EMAIL_TEMPLATES:  'VIEW_EMAIL_TEMPLATES',
  EDIT_EMAIL_TEMPLATES:  'EDIT_EMAIL_TEMPLATES',
  // Logs
  VIEW_LOGS:             'VIEW_LOGS',
  // Testimonials
  VIEW_TESTIMONIALS:     'VIEW_TESTIMONIALS',
  CREATE_TESTIMONIAL:    'CREATE_TESTIMONIAL',
  EDIT_TESTIMONIAL:      'EDIT_TESTIMONIAL',
  DELETE_TESTIMONIAL:    'DELETE_TESTIMONIAL',
}

export const ROLE_PERMISSIONS = {
  SUPER_ADMIN: Object.values(PERMISSIONS),

  SALES_MANAGER: [
    PERMISSIONS.VIEW_ALL_INQUIRIES,
    PERMISSIONS.ASSIGN_INQUIRY,
    PERMISSIONS.UPDATE_INQUIRY_STATUS,
    PERMISSIONS.ADD_INQUIRY_NOTE,
    PERMISSIONS.EXPORT_CRM,
    PERMISSIONS.VIEW_PRODUCTS,
    PERMISSIONS.VIEW_GALLERY,
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.VIEW_LOGS,
    PERMISSIONS.VIEW_TESTIMONIALS,
  ],

  SALES_EXECUTIVE: [
    PERMISSIONS.VIEW_OWN_INQUIRIES,
    PERMISSIONS.UPDATE_INQUIRY_STATUS,
    PERMISSIONS.ADD_INQUIRY_NOTE,
    PERMISSIONS.VIEW_PRODUCTS,
  ],

  MARKETING_MANAGER: [
    PERMISSIONS.VIEW_EMAIL_TEMPLATES,
    PERMISSIONS.EDIT_EMAIL_TEMPLATES,
    PERMISSIONS.VIEW_LOGS,
  ],

  CONTENT_EDITOR: [
    PERMISSIONS.VIEW_PRODUCTS,
    PERMISSIONS.CREATE_PRODUCT,
    PERMISSIONS.EDIT_PRODUCT,
    PERMISSIONS.VIEW_GALLERY,
    PERMISSIONS.CREATE_GALLERY,
    PERMISSIONS.EDIT_GALLERY,
    PERMISSIONS.VIEW_TESTIMONIALS,
    PERMISSIONS.CREATE_TESTIMONIAL,
    PERMISSIONS.EDIT_TESTIMONIAL,
    PERMISSIONS.DELETE_TESTIMONIAL,
  ],
}
